import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import Navigation from "~/components/navigation";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />
        </>
    );
};

export default Home;
