import Head from "next/head";

// Here so we do not get 404, golbal layout handles redirecting to a tenant / getting-started
const Index = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </>
    );
};

export default Index;
